language: cpp
compiler: gcc

addons:
  apt:
    update: true
    packages:
      - libopenmpi-dev
      - liblapack-dev
      - libscalapack-mpi-dev
      - doxygen

jobs:
  include:
    - name: "Make with MPI"
      script:
        - make
        - make tests
        - mpiexec -np 2 tests/tensor_test.out

    - name: "CMake with MPI"
      script:
        - mkdir build && cd build
        - cmake ../
        - make tensor_tests
        - mpiexec -np 2 tests/tensor_test

    - name: "CMake without MPI"
      script:
        - mkdir build && cd build
        - cmake -DENABLE_MPI=OFF ../
        - make tensor_tests
        - ./tests/tensor_test

    - stage: deploy
      name: "Doxygen"
      script:
        - make doc
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: doc/doxygen/html
        on:
          branch: master
