language: cpp
compiler: gcc

addons:
  apt:
    update: true
    packages:
      - libopenmpi-dev
      - liblapack-dev
      - libscalapack-mpi-dev
      - doxygen

script:
  - make
  - make doc
  - make tests

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: doc/doxygen/html
  on:
    branch: master
