language: cpp
compiler: gcc

addons:
  apt:
    update: true
    packages:
      - libopenmpi-dev
      - liblapack-dev
      - libscalapack-mpi-dev
      - doxygen

jobs:
  include:
    - name: "Make with MPI"
      script:
        - make
        - make tests
        - mpiexec -np 2 tests/tensor_test.out

    - name: "CMake with MPI"
      script:
        - mkdir build && cd build
        - cmake -DBUILD_TESTS=ON ../
        - VERBOSE=1 make
        - ctest -V

    - name: "CMake without MPI"
      script:
        - mkdir build && cd build
        - cmake -DENABLE_MPI=OFF -DBUILD_TESTS=ON ../
        - VERBOSE=1 make
        - ctest -V

    - stage: deploy
      name: "Doxygen"
      script:
        - mkdir build && cd build
        - cmake -DBUILD_DOCS=ON ../
        - make doxygen
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: build/doc/doxygen/html
        on:
          branch: master
