var searchData=
[
  ['range_666',['range',['../namespacemptensor.html#a6b444611f676dfab6ea443d6a099249f',1,'mptensor::range(const size_t start, const size_t stop)'],['../namespacemptensor.html#af06165bd221d57be877bfcedc4a56bb9',1,'mptensor::range(const size_t stop)']]],
  ['rank_667',['rank',['../classmptensor_1_1Tensor.html#a19f1ae095b8999437b446e3fd3b94ea5',1,'mptensor::Tensor']]],
  ['replace_5fmatrix_5fdata_668',['replace_matrix_data',['../namespacemptensor_1_1lapack.html#abccf86a79bd749446e69de739153dfd2',1,'mptensor::lapack::replace_matrix_data(const Matrix&lt; C &gt; &amp;M, const std::vector&lt; int &gt; &amp;dest_rank, const std::vector&lt; size_t &gt; &amp;local_position, Matrix&lt; C &gt; &amp;M_new)'],['../namespacemptensor_1_1lapack.html#a1756a93b68b71d8a4a41a7188b6080e0',1,'mptensor::lapack::replace_matrix_data(const std::vector&lt; C &gt; &amp;V, const std::vector&lt; int &gt; &amp;dest_rank, const std::vector&lt; size_t &gt; &amp;local_position, Matrix&lt; C &gt; &amp;M_new)'],['../namespacemptensor_1_1matrix__interface.html#ae8e79d7b26dbb3100ef1e0a057d9ebaa',1,'mptensor::matrix_interface::replace_matrix_data(const Matrix&lt; C &gt; &amp;M, const std::vector&lt; int &gt; &amp;dest_rank, const std::vector&lt; size_t &gt; &amp;local_position, Matrix&lt; C &gt; &amp;M_new)'],['../namespacemptensor_1_1matrix__interface.html#ad4c0a3f2e8a937bd16e748c6e80fa1db',1,'mptensor::matrix_interface::replace_matrix_data(const std::vector&lt; C &gt; &amp;V, const std::vector&lt; int &gt; &amp;dest_rank, const std::vector&lt; size_t &gt; &amp;local_position, Matrix&lt; C &gt; &amp;M_new)'],['../namespacemptensor_1_1scalapack.html#a1aad24b54923febd536765ad62c42b73',1,'mptensor::scalapack::replace_matrix_data(const Matrix&lt; C &gt; &amp;M, const std::vector&lt; int &gt; &amp;dest_rank, const std::vector&lt; size_t &gt; &amp;local_position, Matrix&lt; C &gt; &amp;M_new)'],['../namespacemptensor_1_1scalapack.html#ae112f9ed69393b8d41712e75343b7fd4',1,'mptensor::scalapack::replace_matrix_data(const std::vector&lt; C &gt; &amp;V, const std::vector&lt; int &gt; &amp;dest_rank, const std::vector&lt; size_t &gt; &amp;local_position, Matrix&lt; C &gt; &amp;M_new)']]],
  ['reshape_669',['reshape',['../group__ShapeChange.html#ga9df9d388f7dae0a2bb13e5828896bb00',1,'mptensor']]],
  ['resize_670',['resize',['../classmptensor_1_1Index.html#a4941093db035ea4ada8623146a6f184b',1,'mptensor::Index']]],
  ['result_671',['result',['../classexamples_1_1benchmark_1_1Timer.html#ac4be763872bf05d960d1c1c6ca4c9dfd',1,'examples::benchmark::Timer']]],
  ['rsvd_672',['rsvd',['../group__Random.html#ga3bf92e82d6d7d3de9371c30ac8027a0b',1,'mptensor::rsvd(const Tensor&lt; Matrix, C &gt; &amp;a, const Axes &amp;axes_row, const Axes &amp;axes_col, Tensor&lt; Matrix, C &gt; &amp;u, std::vector&lt; double &gt; &amp;s, Tensor&lt; Matrix, C &gt; &amp;vt, const size_t target_rank, const size_t oversamp)'],['../group__Random.html#ga87f4f269290e036d4418844e550a50a1',1,'mptensor::rsvd(const Tensor&lt; Matrix, C &gt; &amp;a, const Axes &amp;axes_row, const Axes &amp;axes_col, Tensor&lt; Matrix, C &gt; &amp;u, std::vector&lt; double &gt; &amp;s, Tensor&lt; Matrix, C &gt; &amp;vt, const size_t target_rank)'],['../group__Random.html#gac6bde631b6577956d27126a8e4755ce4',1,'mptensor::rsvd(Func1 &amp;multiply_row, Func2 &amp;multiply_col, const Shape &amp;shape_row, const Shape &amp;shape_col, Tensor&lt; Matrix, C &gt; &amp;u, std::vector&lt; double &gt; &amp;s, Tensor&lt; Matrix, C &gt; &amp;vt, const size_t target_rank, const size_t oversamp)'],['../group__Random.html#gadf00f941c595922a4d1e5565d34e0bdc',1,'mptensor::rsvd(Func1 &amp;multiply_row, Func2 &amp;multiply_col, const Shape &amp;shape_row, const Shape &amp;shape_col, Tensor&lt; Matrix, C &gt; &amp;u, std::vector&lt; double &gt; &amp;s, Tensor&lt; Matrix, C &gt; &amp;vt, const size_t target_rank)']]]
];
