name: docs

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: apt
      run: |
        sudo apt update
        sudo apt install -y doxygen graphviz

    - name: Generate Doxygen Documentation
      working-directory: ${{ github.workspace }}/doc/doxygen
      run: doxygen Doxyfile
      
    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v5.0.0
      with:
          path: ${{ github.workspace }}/doc/doxygen/html

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
